#!/bin/bash
# read from file given as argv[1] ($1) and print factors for each num in file

FILE=$1

while read NUMBERS;
do
    factors=($(factor $NUMBERS))
    echo "$NUMBERS=$(($NUMBERS/${factors[1]}))*${factors[1]}"
done < $FILE
